export const authConstants = {
  USER_LOGIN_REQUEST: "USER_LOGIN_REQUEST",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAILURE: "USER_LOGIN_FAILURE",
  USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
  USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
  USER_REGISTER_FAILURE: "USER_REGISTER_FAILURE",
  USER_SIGNOUT_REQUEST: "USER_SIGNOUT_REQUEST",
  USER_SIGNOUT_SUCCESS: "USER_SIGNOUT_SUCCESS",
  USER_SIGNOUT_FAILURE: "USER_SIGNOUT_FAILURE",
  EMAIL_VERIFICATION_REQUEST: "EMAIL_VERIFICATION_REQUEST",
  EMAIL_VERIFICATION_SUCCESS: "EMAIL_VERIFICATION_SUCCESS",
  EMAIL_VERIFICATION_FAILURE: "EMAIL_VERIFICATION_FAILURE",
  OTP_SEND_REQUEST: "OTP_SEND_REQUEST",
  OTP_SEND_SUCCESS: "OTP_SEND_SUCCESS",
  OTP_SEND_FAILURE: "OTP_SEND_FAILURE",
  GET_USER_BY_TOKEN_REQUEST: "GET_USER_BY_TOKEN_REQUEST",
  GET_USER_BY_TOKEN_SUCCESS: "GET_USER_BY_TOKEN_SUCCESS",
  GET_USER_BY_TOKEN_FAILURE: "GET_USER_BY_TOKEN_FAILURE",
  UPDATE_USER_PROFILE_REQUEST: "UPDATE_USER_PROFILE_REQUEST",
  UPDATE_USER_PROFILE_SUCCESS: "UPDATE_USER_PROFILE_SUCCESS",
  UPDATE_USER_PROFILE_FAILURE: "UPDATE_USER_PROFILE_FAILURE",
  PASSWORD_CHANGE_REQUEST: "PASSWORD_CHANGE_REQUEST",
  PASSWORD_CHANGE_SUCCESS: "PASSWORD_CHANGE_SUCCESS",
  PASSWORD_CHANGE_FAILURE: "PASSWORD_CHANGE_FAILURE",
};

export const shopConstants = {
  CREATE_SHOP_REQUEST: "CREATE_SHOP_REQUEST",
  CREATE_SHOP_SUCCESS: "CREATE_SHOP_SUCCESS",
  CREATE_SHOP_FAILURE: "CREATE_SHOP_FAILURE",
  GET_BASIC_SHOP_DETAILS_REQUEST: "GET_BASIC_SHOP_DETAILS_REQUEST",
  GET_BASIC_SHOP_DETAILS_SUCCESS: "GET_BASIC_SHOP_DETAILS_SUCCESS",
  GET_BASIC_SHOP_DETAILS_FAILURE: "GET_BASIC_SHOP_DETAILS_FAILURE",
  GET_SHOP_SETTINGS_REQUEST: "GET_SHOP_SETTINGS_REQUEST",
  GET_SHOP_SETTINGS_SUCCESS: "GET_SHOP_SETTINGS_SUCCESS",
  GET_SHOP_SETTINGS_FAILURE: "GET_SHOP_SETTINGS_FAILURE",
  GET_SHOP_BY_SLUG_REQUEST: "GET_SHOP_BY_SLUG_REQUEST",
  GET_SHOP_BY_SLUG_SUCCESS: "GET_SHOP_BY_SLUG_SUCCESS",
  GET_SHOP_BY_SLUG_FAILURE: "GET_SHOP_BY_SLUG_FAILURE",
};

export const categoryConstants = {
  GET_ALL_CATEGORIES_REQUEST: "GET_ALL_CATEGORIES_REQUEST",
  GET_ALL_CATEGORIES_SUCCESS: "GET_ALL_CATEGORIES_SUCCESS",
  GET_ALL_CATEGORIES_FAILURE: "GET_ALL_CATEGORIES_FAILURE",
};

export const productConstants = {
  GET_PRODUCT_BY_SLUG_REQUEST: "GET_PRODUCT_BY_SLUG_REQUEST",
  GET_PRODUCT_BY_SLUG_SUCCESS: "GET_PRODUCT_BY_SLUG_SUCCESS",
  GET_PRODUCT_BY_SLUG_FAILURE: "GET_PRODUCT_BY_SLUG_FAILURE",
  SEARCH_PRODUCTS_REQUEST: "SEARCH_PRODUCTS_REQUEST",
  SEARCH_PRODUCTS_SUCCESS: "SEARCH_PRODUCTS_SUCCESS",
  SEARCH_PRODUCTS_FAILURE: "SEARCH_PRODUCTS_FAILURE",
  IMAGE_SEARCH_PRODUCTS_REQUEST: "IMAGE_SEARCH_PRODUCTS_REQUEST",
  IMAGE_SEARCH_PRODUCTS_SUCCESS: "IMAGE_SEARCH_PRODUCTS_SUCCESS",
  IMAGE_SEARCH_PRODUCTS_FAILURE: "IMAGE_SEARCH_PRODUCTS_FAILURE",
};
